### ISSUE TITLE
Schematic Submission 

### ISSUE THREAD

**Issue by timChase98** [cedricleonardo/ECE-388-Project#1]
- [ ] Review the submission guidelines [HERE](https://github.com/timChase98/388Example)
- [ ] All project files should be version controlled
- [ ] C3 should point to down to gnd not up
- [ ] Use a 2 pin connector for the load connection not a DC jack 
- [ ] How does your current sense measurement work? 
 
Please address these issues and push your changes. Then create a new release, increment the tag and close this issue. I will review the changes and mark this as complete or reopen the issue with additional feedback.

**Comment by cedricleonardo** [comment]
For the current sense measurement I was thinking of using analog read and ohms law to get the current going through the op amp. I would then display this value, the voltage, and load on my LCD.

**Comment by timChase98** [comment]
- [x] Change R1 to 10k
- [x] Change R11 and R9 to 1k
- [x] Add a pull up resistor to the CS pin on U$1
- [x] Look into protection for reverse voltage on test connector

**Comment by timChase98** [comment]
- [x] Add your eagle files to the repo
- [x] A negative voltage on the test connector would still kill your ADC.  Move the protection fet onto the negative line

**Comment by timChase98** [comment]
I'll accept this.  You can move onto layout.  Clean up some of your nets and I'll give it a pass

**Comment by cedricleonardo** [comment]
I cleaned up some of the nets, especially around the op amps.

**Comment by timChase98** [comment]
Rotate the LCD so all the text is the right way and you are good to go.

**Comment by cedricleonardo** [comment]
I rotated the LCD

**Comment by timChase98** [comment]
Looks good.  I'll give it a pass
