### ISSUE TITLE
Board Submission

### ISSUE THREAD

**Issue by timChase98** [cedricleonardo/ECE-388-Project#2]
- [ ] Review the submission guidelines [HERE](https://github.com/timChase98/388Example)
- [ ] All project files should be version controlled
- [ ] Boards will not be graded unless both Eagle files and correctly generated Gerber files are present
- [ ] All traces should hit the center of pads
- [ ] Power traces should have a minimum width of 12 mil or run through a plane
- [ ] Silkscreen labels must include
  - [ ] Your Name
  - [ ] Project Name
  - [ ] Date
  - [ ] Version/Rev
  - [ ] Github Link
- [ ] Your project would fit on a much smaller board
- [ ] Placement of fiducials should be 
  - [ ] FID1 lower left 
  - [ ] FID2 upper left
  - [ ] FID3 lower right
- [ ] Traces should never intersect at an acute angle 
- [ ] Shorter traces are better 
- [ ] Increase the trace width for thermal relief for the power supply 

These are initial comments meant to guide you though the layout process.  I will not look at your board again until your schematic passes review.  This is to reduce the workload on you by limiting the number of times you need to relayout your board due to schematic errors.  

Please address these issues and push your changes. Then create a new release, increment the tag and close this issue. I will review the changes and mark this as complete or reopen the issue with additional feedback.

**Comment by timChase98** [comment]
- [x] check datasheet for DC jack for correct footprint 
- [x] check stock sheet for correct footprints for ICs 
- [x] Run a DRC and ERC 
- [x] Q1 is too close to the edge of the board.  
- [ ] You have silkscreen overlapping pads and other silkscreen

**Comment by cedricleonardo** [comment]
@timChase98 was my board approved, I just wanted to make sure I meet the deadline

**Comment by timChase98** [comment]
Font size is too small.  Run normalize text ulp and set to 8 mil stroke width

**Comment by cedricleonardo** [comment]
Fixed font size to 8 mil stroke

**Comment by timChase98** [comment]
Your board will be sent to fab
